---
- name: Check if user has lingering enabled.
  ansible.builtin.command:
    cmd: "ls /var/lib/systemd/linger"
  changed_when: false
  register: linger

- name: Enable linger for user {{ pihole_user }}
  become: true
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ pihole_user }}"
  changed_when: true
  when: "pihole_user not in linger.stdout"

- name: Ensure port 53 can be accessed by rootless containers.
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: '53'
    sysctl_set: true
    state: present
    reload: true

- name: Get firewalld service status.
  ansible.builtin.systemd:
    name: firewalld
  register: firewalld_status

- name: Ensure ports are open in firewall.
  when: firewalld_status.status.ActiveState == 'active'
  block:
    - name: Ensure dns service is open in firewall.
      become: true
      ansible.posix.firewalld:
        state: enabled
        service: dns
        immediate: true
        permanent: true

    - name: Ensure custom dns port is open in firewall.
      when: pihole_dns_port != '53'
      become: true
      ansible.posix.firewalld:
        state: enabled
        port: "{{ item }}"
        immediate: true
        permanent: true
      loop:
        - "53/tcp"
        - "53/udp"

- name: Run tasks under user {{ pihole_user }}.
  become: true
  become_user: "{{ pihole_user }}"
  block:
    - name: Include app tasks.
      ansible.builtin.include_tasks: app.yml
